### ISSUE TITLE
Update the pluing and 

### ISSUE THREAD

**Issue by rabin-io** [seregatte/AnsibleSnippets#1]
1. Is this plugin still maintained ? 
1. Is there a way to auto-update/generate the snippets from the site documentations ?

**Comment by seregatte** [comment]
Hello.

1. Yes, but is outdated. (I'll solve this as soon as possible)
2. In the next releases I'll automate based on ansible's command line documentation.

Thank you for your support.

**Comment by seregatte** [comment]
I released today a new version.

Thank you for your support.

**Comment by rabin-io** [comment]
Thanks.
Just curious, how do you currently create the snippets ?

**Comment by seregatte** [comment]
Sorry, I saw your question too later.
