### ISSUE TITLE
Could you follow ansible evolution

### ISSUE THREAD

**Issue by EricDele** [seregatte/AnsibleSnippets#4]
Hello

Please could you update your package to follow the ansible recommandations ?
You have a PR for using become instead off sudo, could you change too the = in : for the parameters ?

Many thanks

**Comment by seregatte** [comment]
Hello @EricDele I merged #2 .

Thank you for your contribution!

**Comment by EricDele** [comment]
Hello

Thanks for this, but what about the equal sign replaced by ":" for the parameters ? 

Regards

**Comment by seregatte** [comment]
I rewrote the snippet generator following Ansible 2.4.1.0 documentation, I believe that we are updated now.
